'use client';
import Link from 'next/link';
import { useTheme } from '@/app/context/ThemeContext';

export default function TermsPage() {
  const { isDark } = useTheme();

  return (
    <div className={`min-h-screen p-8 md:p-20 transition-colors duration-500 ${isDark ? 'bg-[#030305] text-white/80' : 'bg-slate-50 text-slate-800'}`}>
      <div className="max-w-3xl mx-auto pt-20">
        <Link href="/" className="inline-block mb-10 text-sm font-bold uppercase tracking-widest hover:text-amber-400 transition-colors">
          ← Back to Vault
        </Link>
        <h1 className="text-4xl md:text-5xl font-black uppercase tracking-[0.2em] mb-8 bg-clip-text text-transparent bg-gradient-to-r from-amber-400 to-orange-600">
          Terms of Service
        </h1>
        <div className={`space-y-6 text-lg leading-relaxed ${isDark ? 'text-white/60' : 'text-slate-600'}`}>
          <p>Last Updated: May 14, 2026</p>
          
          <h3 className="text-2xl font-bold text-white mt-8">1. Acceptance of Terms</h3>
          <p>By accessing and using The Vault Engine, you accept and agree to be bound by the terms and provision of this agreement.</p>
          
          <h3 className="text-2xl font-bold text-white mt-8">2. Use License</h3>
          <p>Permission is granted to temporarily use the Minigame Hub for personal, non-commercial transitory viewing or streaming purposes only. You may not modify, reverse engineer, or commercially distribute the engine source code.</p>
          
          <h3 className="text-2xl font-bold text-white mt-8">3. Fair Play and Limitations</h3>
          <p>The Vault Engine is provided "as is". While we guarantee high-quality visual outputs, we are not liable for external wagers, real-world prizes, or agreements made between broadcasters and their audiences based on the outcomes generated by our RNG systems.</p>
        </div>
      </div>
    </div>
  );
}
